type Query {
  note(id: String!): Note
  notes(first: Int): [Note!]!
  user(id: String!): User
  users(first: Int): [User!]!
}

type Mutation {
  bar: String!
}

schema {
  query: Query
  mutation: Mutation
}

type Note {
  id: String!
  author: User!
  content: String!
}

type User {
  id: String!
  name: String!
  notes: [Note!]!
}
